### ISSUE TITLE
Extend the database with easy image questions

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#122]

**Comment by Altishofer** [comment]
ee0a45d93064f8735e4a04aa24b24bcb43d845cd mistakenly committed to wrong devTask ID

**Comment by Altishofer** [comment]
tested image mode empirically and fixed bug with 7847b8c236fc2800209daf5175408d30567b8edd and cbc6d625e7ada2bb4b2883cbe181568e80b581d2
