### ISSUE TITLE
the database is hosted on google, persistent and set up with protected Github secrets

### ISSUE THREAD

**Issue by Altishofer** [sopra-fs23-group-10/sopra-fs23-group-10-server#77]

**Comment by Altishofer** [comment]
successful testing in google cloud by verifying database with pgAdmin

**Comment by Chopstew** [comment]
Gets tested by the various integration tests, e.g., by **createQuestion_success** in _QuestionServiceIntegrationTest_, implemented with commit b5ad733e97928adcb3b783c4084bb7a84c6c933b
