### ISSUE TITLE
The answer received during single mode are stored in the backend.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#94]

**Comment by Altishofer** [comment]
Empirically successfully tested with client in addition to backend-tests

**Comment by Chopstew** [comment]
Gets tested by **intermediateResults_OnlyOneUserAnswered_success** in _GameControllerServiceTest_, implemented with commit  05b9ea9a9667c9aa7d6d49f5dfddb192aa6ea4d3
