### ISSUE TITLE
Make intermediate scores retrievable from the backend during Single Mode

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#98]

**Comment by Altishofer** [comment]
implemented and successfully tested by @Altishofer  with another dev task and the major following commits 446cf4653123f72d0afb8967fd3f778033d4d54b and 2fdd7f51b70f95fc54ad1c6cbf5c2922bf3e0e8c

**Comment by Chopstew** [comment]
Gets tested by **intermediateGame_whenValid_returnResults_200** in _GameControllerTest_
